GET http://localhost:3000 HTTP/1.1

###
GET http://localhost:3000/github/user HTTP/1.1

###
GET https://api.github.com/repos/OWNER/REPO/commitst HTTP/1.1
Accept: application/vnd.github+json
Authorization: Bearer <YOUR-TOKEN>
X-GitHub-Api-Version: 2022-11-28
